name: images_gallery
description: an easy way to display an images gallery in flutter, a bit like samsung's gallery
version: 0.0.6
repository: https://github.com/codebird/flutter_gallery_images.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
